apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-{{ .Values.django.name }}-deployment
  namespace: {{ .Values.env }}
  labels:
    deployment-name: {{ .Values.env }}-{{ .Values.django.name }}-deployment
    deployment-env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.django.replicas }}
  strategy:
#Running multiple versions of an application at the same time, stop old pods once new one is up and running
    type: RollingUpdate
    rollingUpdate:
#The maximum number of Pods that can be created over the desired number of Pods
      maxSurge: 100%
#The maximum number of Pods that can be unavailable during the update process
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Values.django.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-{{ .Values.django.name }}
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name:  {{ .Values.env }}-{{ .Values.django.name }}-container
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.django.port }}
        resources:
          limits:
            cpu: {{ .Values.django.cpu_limits }}
          requests:
            cpu: {{ .Values.django.cpu_requests }}
        livenessProbe:
          httpGet:
             path: {{ .Values.health_check }}
             port: {{ .Values.django.targetPort }}
          initialDelaySeconds: {{ .Values.health_initialDelaySeconds }}
          timeoutSeconds: {{ .Values.health_timeoutSeconds }}
          periodSeconds: {{ .Values.health_periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.health_check }}
            port: {{ .Values.django.targetPort }}
          initialDelaySeconds: {{ .Values.health_initialDelaySeconds }}
          timeoutSeconds: {{ .Values.health_timeoutSeconds }}
          periodSeconds: {{ .Values.health_periodSeconds }}
